# This workflow is designed for building and testing a Node.js project with PostgreSQL

name: Node.js.test_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events for the "main" branch
  pull_request:
    branches:
      main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job is responsible for building the Node.js project
  build:
    name: node.js.test build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Define the PostgreSQL service
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
         - 5432:5432

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Check out the repository to the runner's working directory
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment with the specified version
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Use Node.js version 20

      # Step 3: Install project dependencies using npm
      - name: Install dependencies
        run: npm install

      # Step 4: Set up environment variables from GitHub secrets
      - run: |
          echo > .env
          ls -al | grep .env
          echo NODE_ENV=${{ secrets.ENVIRONMENT }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo HOSTNAME=${{ secrets.HOSTNAME }} >> .env

      # Step 5: Run tests using npm
      - name: Run tests
        run: npm test
