name: Packer Build CI

# Trigger the workflow only on push to the main branch (after a PR is merged).
on:
  push:
    branches: [ "main" ] # Only trigger when code is pushed to the 'main' branch.

jobs:
  packer-build:
    name: Packer Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Install Packer using HashiCorp GitHub Action
      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        with:
          version: 'latest' # Use the latest version of Packer.

      # Step 4: Zip the web application files (this step was missing)
      - name: Zip the web application
        run: |
          zip -r webapp.zip ./
          ls -al # List the files to confirm the zip was created.

      # Step 5: Format the Packer configuration
      - name: Packer Format
        id: format
        run: packer fmt ./aws.pkr.hcl # Format the Packer configuration files.

      # Step 6: Initialize Packer to download any necessary plugins
      - name: Packer Init
        id: init
        run: |
          packer init ./aws.pkr.hcl # Initialize the Packer configuration file (aws.pkr.hcl).

      # Step 7: Validate the Packer configuration
      - name: Packer Validate
        id: validate
        run: |
          packer validate ./aws.pkr.hcl # Validate the Packer configuration.

      # Step 8: Run the Packer build
      # packer build ./aws.pkr.hcl # Build the AMI using Packer.
      - name: Run Packer build
        id: build
        run: |
          packer build aws.pkr.hcl
